name: "Lint"
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
permissions:
  contents: "read"
  pull-requests: "read"
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup"
        uses: "actions/setup-go@v5"
        with:
          go-version: "^1.22"
      - name: "Lint"
        uses: "golangci/golangci-lint-action@v4"
        with:
          args: "-E gofmt -E goimports -E revive"
